install:
  - choco install gitversion.portable -pre -y

configuration: Release

assembly_info:
  patch: false

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build_script:
  - cmd: dotnet build DKW.NMEA\DKW.NMEA.csproj -c %CONFIGURATION% -version "%GitVersion_NuGetVersion%"

after_build:
  - cmd: dotnet pack DKW.NMEA\DKW.NMEA.nuspec -c %CONFIGURATION% -version "%GitVersion_NuGetVersion%"
  
deploy:
  provider: NuGet
  api_key:
    secure: oKBi9hZNM35lgEr9CbJA5yJHMMdNzBiC0BeTCfTVf4yQhgJ1lytVf57/dV9yk3bo
  skip_symbols: false
  artifact: /.*\.nupkg/
