install:
  - choco install gitversion.portable -pre -y

configuration: Release

assembly_info:
  patch: false

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: DKW.NMEA\DKW.NMEA.csproj

after_build:
  - cmd: nuget pack DKW.NMEA\DKW.NMEA.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  
deploy:
  provider: NuGet
  api_key:
    secure: oKBi9hZNM35lgEr9CbJA5yJHMMdNzBiC0BeTCfTVf4yQhgJ1lytVf57/dV9yk3bo
  skip_symbols: false
  artifact: /.*\.nupkg/
